regress: slightly improve the test suite infrastructure

diff --git a/regress/peek/Makefile b/regress/peek/Makefile
--- a/regress/peek/Makefile
+++ b/regress/peek/Makefile
@@ -1,14 +1,15 @@
 REGRESS_FILE=	peek
+REGRESS_TYPE=	bin
 
 #	output			sample
-REGRESS_TARGET=	\
+REGRESS_TEST= \
 	test_erf		test.erf \
 	test_pcap		test.pcap \
 	test_pcap_swap		test_be.pcap \
 	test_pcapng		test.pcapng \
 
 all:
-	@set `echo $(REGRESS_TARGET)`; \
+	@set `echo $(REGRESS_TEST)`; \
 	while : ; do \
 		case $$# in \
 		0) break;; \
@@ -17,7 +18,7 @@ all:
 		TRACE=$(.CURDIR)/../../sample/$$2; \
 		[ ! -f $$TRACE ] && \
 		    echo "$$1 failed: $$TRACE not found" && exit 1; \
-		$(.CURDIR)/../../bin/$(REGRESS_FILE)/$(REGRESS_FILE) $$TRACE | \
-		    diff -au $$1 - || (echo "$$1 failed" && exit 1); \
+		$(.CURDIR)/../../$(REGRESS_TYPE)/$(REGRESS_FILE)/$(REGRESS_FILE) \
+		    $$TRACE | diff -au $$1 - || (echo "$$1 failed" && exit 1); \
 		shift; shift; \
 	done
