make: make BSD make the native build glue
It's been fun while it lasted, but BSD make is available on
all sane architectures.  Please use it.

diff --git a/regress/peek/Makefile b/regress/peek/Makefile
--- a/regress/peek/Makefile
+++ b/regress/peek/Makefile
@@ -1,11 +1,10 @@
-BASEDIR=../..
-
-FILE=	$(BASEDIR)/bin/peek/peek
+REGRESS_FILE=	peek
 
 #	output			sample
 REGRESS_TARGET=	\
 	test_erf		test.erf \
 	test_pcap		test.pcap \
+	test_pcap_swap		test_be.pcap \
 	test_pcapng		test.pcapng \
 
 all:
@@ -15,10 +14,10 @@ all:
 		0) break;; \
 		1) echo "$$1 failed: missing arguments"; exit 1;; \
 		esac; \
-		TRACE=$(BASEDIR)/sample/$$2; \
+		TRACE=$(.CURDIR)/../../sample/$$2; \
 		[ ! -f $$TRACE ] && \
 		    echo "$$1 failed: $$TRACE not found" && exit 1; \
-		$(FILE) $$TRACE | diff -au $$1 - || \
-		    (echo "$$1 failed" && exit 1); \
+		$(.CURDIR)/../../bin/$(REGRESS_FILE)/$(REGRESS_FILE) $$TRACE | \
+		    diff -au $$1 - || (echo "$$1 failed" && exit 1); \
 		shift; shift; \
 	done
